using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace SignalrDotnetCoreApi
{
    public class SwaggerDocumentFilter : IDocumentFilter
    {
        public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
        {
            swaggerDoc.Servers = new List<OpenApiServer>
            {
                new OpenApiServer
                {
                    Description = "DEV server",
                    Url = "http://localhost:1234",
                    Variables = CreateVariables(1234, 1235, "v1")
                },
                new OpenApiServer
                {
                    Description = "INT server",
                    Url = "http://localhost:5678",
                    Variables = CreateVariables(5678, 5679, "v2")
                }
            };

            swaggerDoc.ExternalDocs = new OpenApiExternalDocs
            {
                Description = "Open API Specification (OAS)",
                Url = new Uri("http://spec.openapis.org/oas/v3.0.3")
            };
            
            //Non customizable:
            // - swaggerDoc.Components: API input and output data models, auto-generated by Swashbuckle
            // - swaggerDoc.Info: already instantiated in SwaggerDoc
            // - swaggerDoc.Tags: tags are API controller root names, auto-generated by Swashbuckle
        }

        private static ConcurrentDictionary<string, OpenApiServerVariable> CreateVariables(int defaultPortNumber, int alternativePortNumber, string basePath)
        {
            var variables = new ConcurrentDictionary<string, OpenApiServerVariable>();

            variables.TryAdd("UserName", new OpenApiServerVariable
            {
                Default = "Jiangong",
                Description = "Demo User"
            });

            variables.TryAdd("Port", new OpenApiServerVariable
            {
                Default = defaultPortNumber.ToString(),
                Description = "Port number",
                Enum = new List<string>()
                {
                    defaultPortNumber.ToString(),
                    alternativePortNumber.ToString()
                }
            });

            variables.TryAdd("BasePath", new OpenApiServerVariable
            {
                Default = basePath
            });

            return variables;
        }
    }
}
